language: php
php:
  - 7.3

dist: bionic

git:
  depth: false

cache:
  yarn: true
  directories:
    - ".yarn"
    - "vendor"

env:
  global:
    - SKIP_BUILD=`[[ $TRAVIS_COMMIT_MESSAGE == *"[skipbuild]"* ]]; echo $?`

# master: build & sonar
# pull intern: build & sonar (2 builds, 1 met type pull_request, 1 met type push)
# pull extern: build
jobs:
  include:
    - stage: build
      services: mysql
      before_install: nvm install 12
      script: ./bin/ci/build.sh
      deploy:
        provider: script
        script: ./bin/ci/deploy.sh
        skip_cleanup: true
        on:
          branch: master
      if: type != pull_request OR fork = true
    - stage: analysis
      script: sonar-scanner
      if: (branch = master OR type = pull_request) AND fork = false
      addons:
        sonarcloud:
          organization: "csrdelft"

stages:
  - build
  - analysis

script: skip
