cms-overzicht:
  path: /pagina
  controller: CsrDelft\controller\CmsPaginaController::overzicht
  defaults: { _mag: P_LOGGED_IN }

cms-bekijken:
  path: /pagina/{naam}
  controller: CsrDelft\controller\CmsPaginaController::bekijken
  defaults: { _mag: P_PUBLIC }

cms-bewerken:
  path: /pagina/bewerken/{naam}
  controller: CsrDelft\controller\CmsPaginaController::bewerken
  defaults: { _mag: P_LOGGED_IN }

cms-verwijderen:
  path: /pagina/verwijderen/{naam}
  controller: CsrDelft\controller\CmsPaginaController::verwijderen
  defaults: { _mag: P_ADMIN }
