corvee-punten-beheer:
  path: /corvee/punten
  controller: CsrDelft\controller\maalcie\BeheerPuntenController::beheer
  methods: GET
  defaults: { _mag: P_CORVEE_MOD }

corvee-punten-beheer-resetjaar:
  path: /corvee/punten/resetjaar
  controller: CsrDelft\controller\maalcie\BeheerPuntenController::resetjaar
  methods: GET
  defaults: { _mag: P_CORVEE_MOD }

corvee-punten-beheer-wijzigpunten:
  path: /corvee/punten/wijzigpunten/{uid}
  controller: CsrDelft\controller\maalcie\BeheerPuntenController::wijzigpunten
  methods: POST
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_CORVEE_MOD }

corvee-punten-beheer-wijzigbonus:
  path: /corvee/punten/wijzigbonus/{uid}
  controller: CsrDelft\controller\maalcie\BeheerPuntenController::wijzigbonus
  methods: POST
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_CORVEE_MOD }
