app-controller-sub:
  resource: ../lib/controller/**/*.php
  type: attribute

# Deze route is een catch-all als allerlaatste
default:
  path: /{_locale<%app.supported_locales%>}/{naam}/{subnaam}
  controller: CsrDelft\controller\CmsPaginaController::bekijken
  defaults: { naam: thuis, subnaam: '', _mag: 'PUBLIC_ACCESS' }

defaultNoLocale:
  path: /{naam}/{subnaam}
  controller: CsrDelft\controller\CmsPaginaController::bekijken
  defaults: { naam: thuis, subnaam: '', _mag: 'PUBLIC_ACCESS', _locale: nl }
