app-controller-sub:
  resource: ../lib/controller/**/*.php
  type: annotation

# Deze route is een catch-all als allerlaatste
default:
  path: /{_locale<%app.supported_locales%>}/{naam}/{subnaam}
  controller: CsrDelft\controller\CmsPaginaController::bekijken
  defaults: { naam: thuis, subnaam: "", _mag: P_PUBLIC }

defaultNoLocale:
  path: /{naam}/{subnaam}
  controller: CsrDelft\controller\CmsPaginaController::bekijken
  defaults: { naam: thuis, subnaam: "", _mag: P_PUBLIC, _locale: nl}
